### PR TITLE
Lint/formatting and static code analyzer.

### PR DESCRIPTION
**Pull request by fbernaly**
Organize src files and enforce some lint and formatting rules in dart and swift.
Added workflow: static code analyzer.

### CODE REVIEW

**Comment by fbernaly** [comment]
@VNAPNIC: I polish the code using some formatting to make it more production ready. No changes to the functionality of the plugin, just cosmetic fixes to conform with code standards for each language.

**Comment by fbernaly** [comment]
@VNAPNIC : any plan to merge this? I would like to send another PR with turning off presentation method

**Comment by amirulhakim47** [comment]
> @VNAPNIC : any plan to merge this? I would like to send another PR with turning off presentation method

Hi, i'm also looking to use this turning off presentation feature would you mind sharing the method?

**Comment by fbernaly** [comment]
Closing this for lack of interest and inactivity.

**Pull request closed without merging**
